# Generated by Django 4.1.2 on 2023-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolls',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
