# Generated by Django 4.1.2 on 2023-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolls',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dolls',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
