# Generated by Django 4.1.2 on 2023-02-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_dolls_first_name_dolls_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalls.dolls')),
            ],
        ),
    ]
